### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by nobuti** [DRD4-7R/eslint-config-7r-building#4]
- [ ] publish a new version to npm when PR are merged to master

**Comment by tripu** [comment]
FWIW, to deploy to npm automatically for every release (tag) **on Travis CI**, one only has to add this to `.travis.yml`:

```yaml
deploy:
  provider: npm
  email: tech@7r.ventures
  api_key:
    secure: <OUR_NPM_PASSWORD_AS_ENCRYPTED_ON_THE_TRAVIS_SITE>
  on:
    tags: true
    repo: DRD4-7R/eslint-config-7r-building
```

Then, every time we want to release, on a clean `master`:

```bash
npm version [major|minor|patch]
git push --follow-tags
```
